repositories:
  - jytechllc/performance-review

engineers:
  - username: adragon246
    display_name: Andew Dong
  - username: rlee88
    display_name: Ryan Lee
  - username: klee1432
    display_name: Kathryn Lee
  - username: jchen42
    display_name: Joy Chen
  - username: ehsu42
    display_name: Emily Hsu
  - username: snguyen-code
    display_name: Sam Nguyen